routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Auth::routes()
;
Route::get('/', 'WelcomeController@index');

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

//CityController
Route::get('search', 'CityController@search');

//CarController
Route::get('searchBrand', 'CarController@searchBrand');
Route::get('searchModel', 'CarController@searchModel');
Route::get('user/car', 'CarController@index')->name('car.index');
Route::post('user/car', 'CarController@store')->name('car.store');
Route::delete('user/car', 'CarController@destroy')->name('car.destroy');

//TravelController
Route::get('travel/offered', 'TravelController@offered')->name('travel.offered');
Route::get('travel/offered/history', 'TravelController@offeredHistory')->name('travel.offered_history');
Route::get('travel/booked', 'TravelController@booked')->name('travel.booked');
Route::get('travel/booked/history', 'TravelController@bookedHistory')->name('travel.booked_history');
Route::get('travel/{travel}/book', 'TravelController@book')->name('travel.book');
Route::delete('travel/{travel}/cancel_booking', 'TravelController@cancelBooking');
Route::resource('travel', 'TravelController');

//UserImageController
Route::get('image', 'UserImageController@index')->name('image');
Route::post('image/upload', 'UserImageController@upload')->name('image.upload');
Route::delete('image/delete', 'UserImageController@delete')->name('image.delete');

//UpdatePasswordController
Route::get('user/change-password', 'UpdatePasswordController@index')->name('password.form');
Route::put('user/change-password', 'UpdatePasswordController@update')->name('password.update');

//UserController
Route::get('user/edit', 'UserController@edit')->name('user.edit');
Route::get('user/remove', 'UserController@remove')->name('user.remove');
Route::get('user/{user}', 'UserController@show')->name('user.show');
Route::put('user/{user}', 'UserController@update')->name('user.update');
Route::delete('user/{user}', 'UserController@destroy')->name('user.destroy');

//ReviewController
Route::get('review/received', 'ReviewController@received')->name('review.received');
Route::get('review/leaved', 'ReviewController@leaved')->name('review.leaved');
Route::get('review/create/{user}/{travel}', 'ReviewController@create')->name('review.create');
Route::post('review/{user}/{travel}', 'ReviewController@store')->name('review.store');

//HomeController
Route::get('home', 'HomeController@index')->name('home');

app/Models/Review.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Review
 *
 * @package App
 * @property int $id
 * @property int $owner_id
 * @property int $user_id
 * @property int $travel_id
 * @property int $type
 * @property string $score
 * @property string $about
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $owner
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereOwnerId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereScore($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereUserId($value)
 * @mixin \Eloquent
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereTravelId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereType($value)
 */
class Review extends Model
{

    const SCORE = [
        '5' => 'Outstanding',
        '4' => 'Excellent',
        '3' => 'Good',
        '2' => 'Poor',
        '1' => 'Very disappointing',
    ];

    const REVIEWS_PER_PAGE = 5;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'review';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable = [
        'score',
        'about',
        'type',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function owner()
    {
        return $this->belongsTo('App\Models\User', 'owner_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    /**
     * @return string
     */
    public function getLiteralScoreAttribute(): string
    {
        return array_key_exists($this->score, self::SCORE)
            ? self::SCORE[$this->score]
            : 'Unknown score';// const
    }

    /**
     * @return string
     */
    public function getLiteralCreatedAtAttribute(): string
    {
        return date("F jS - g:ia", strtotime($this->created_at));
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 *
 * @package App
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property integer $birth_year
 * @property string $about
 * @property string $car
 * @property string $image
 * @property integer $status
 * @property integer $admin
 * @property integer $password
 * @property integer $remember_token
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Travel[] $passenger
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Review[] $review
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Travel[] $travel
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\UserToTravel[] $usersPassengers
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereAdmin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereBirthYear($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereUpdatedAt($value)
 * @property int|null $car_id
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereCarId($value)
 */
class User extends Authenticatable
{
    use Notifiable;

    const DEFAULT_PROFILE_IMAGE = '/images/default.jpg';
    const PROFILE_IMAGE_PATH = '/uploads/images/profile/';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'phone', 'birth_year', 'about', 'image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    protected static function boot()
    {
        parent::boot();

        static::deleting(function (User $user) {
            $user->passenger()->detach();
            $user->usersPassengers()->delete();
            $user->review()->delete();
            $user->usersReviews()->delete();
            $user->travel()->delete();
            $user->deleteImage();
        });
    }

    public function review()
    {
        return $this->hasMany('App\Models\Review');
    }

    public function usersReviews()
    {
        return $this->belongsTo('App\Models\Review', 'id', 'owner_id');
    }

    public function travel()
    {
        return $this->hasMany('App\Models\Travel');
    }

    public function usersPassengers()
    {
        return $this->hasManyThrough('App\Models\UserToTravel', 'App\Models\Travel');
    }

    public function passenger()
    {
        return $this->belongsToMany('App\Models\Travel', 'user_to_travel');
    }

    public function car()
    {
        return $this->hasOne('App\Models\Car', 'id', 'car_id');
    }

    /**
     * Removes users image
     * return void
     */
    public function deleteImage(): void
    {
        $imagePath = public_path(). self::PROFILE_IMAGE_PATH . $this->image;
        if(isset($this->image) && file_exists($imagePath))
        {
            unlink($imagePath);
        }
    }

    /**
     * @return string
     */
    public function getProfileImageAttribute(): string
    {
        $path = self::PROFILE_IMAGE_PATH;
        $pathToProfileImage = public_path() . $path . $this->image;
        return !empty($this->image) && file_exists($pathToProfileImage) ?
            $path . $this->image : self::DEFAULT_PROFILE_IMAGE;
    }

    /**
     * @return string
     */
    public function getShortNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name{0};
    }

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @return int
     */
    public function getAgeAttribute()
    {
        return date('Y') - $this->birth_year;
    }

    /**
     * @return string
     */
    public function getRegisterMonthAttribute()
    {
        return date("F Y", strtotime($this->created_at));
    }

    /**
     * @return float
     */
    public function getAvgScoreAttribute(): float
    {
        return round($this->review->pluck('score')->avg(), 1);
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateUser;
use App\Services\ReviewService;
use App\Services\TravelService;
use App\Services\UserService;
use App\Models\User;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    /**
     * @var UserService
     */
    private $userService;

    /**
     * @var ReviewService
     */
    private $reviewService;

    /**
     * @var TravelService
     */
    private $travelService;

    /**
     * @var \Illuminate\Contracts\Auth\Authenticatable
     */
    private $user;

    /**
     * @param UserService $userService
     * @param ReviewService $reviewService
     * @param TravelService $travelService
     */
    public function __construct(
        UserService $userService,
        ReviewService $reviewService,
        TravelService $travelService
    ) {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            $this->user = auth()->user();
            return $next($request);
        });

        $this->userService = $userService;
        $this->reviewService = $reviewService;
        $this->travelService = $travelService;
    }

    /**
     * Display the specified User.
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(User $user)
    {
        $reviews = $this->reviewService->findReceived($user->id);
        $countUserTravels = $this->travelService->countOffered($user->id);
        return view('user.show', [
                'user' => $user,
                'reviews' => $reviews ?? null,
                'countUserTravels' => $countUserTravels,
                'reviewsCount' => $reviews->total(),
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        return view('user.edit')->with('user', $this->user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateUser $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UpdateUser $request)
    {
        $userId = $this->userService->updateUser($request, $this->user);
        Session::flash('message', __('Your profile was updated!'));
        return redirect("user/edit");
    }

    /**
     * Show the page for removing User.
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function remove()
    {
        return view('user.remove')->with('user', $this->user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy()
    {
        $this->userService->destroyUser($this->user);
        return redirect("home");
    }

}

resources/views/user/change-password.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    @include('layouts.navtab')
                    <div class="card-body">
                        <div class="row">
                            @include('layouts.sidebar')
                            <div class="col-8">

                                @if (Session::has('success'))
                                    <div class="alert alert-success">{{ Session::get('success') }}</div>
                                @endif
                                @if (Session::has('failure'))
                                    <div class="alert alert-danger">{{ Session::get('failure') }}</div>
                                @endif
                                <form action="{{ route('password.update') }}" method="post">
                                    @csrf
                                    @method('PUT')

                                    <div class="form-group{{ $errors->has('old') ? ' has-error' : '' }} row">
                                        <label for="old" class="col-sm-4 col-form-label text-md-right">{{ __('Old Password') }}</label>

                                        <div class="col-md-6">
                                            <input id="old" type="password"
                                                   class="form-control{{ $errors->has('old') ? ' is-invalid' : '' }}"
                                                   name="old">
                                            @if ($errors->has('old'))
                                                <span class="invalid-feedback" role="alert">
                                                     <strong>{{ $errors->first('old') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }} row">
                                        <label for="password"
                                               class="col-sm-4 col-form-label text-md-right">{{ __('New Password') }}</label>

                                        <div class="col-md-6">
                                            <input id="password" type="password"
                                                   class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                                   name="password">
                                            @if ($errors->has('password'))
                                                <span class="invalid-feedback" role="alert">
                                                     <strong>{{ $errors->first('password') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }} row">
                                        <label for="password-confirm" class="col-sm-4 col-form-label text-md-right">{{ __('Confirm New Password') }}</label>

                                        <div class="col-md-6">
                                            <input id="password-confirm" type="password"
                                                   class="form-control{{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}"
                                                   name="password_confirmation">
                                            @if ($errors->has('password_confirmation'))
                                                <span class="invalid-feedback" role="alert">
                                                     <strong>{{ $errors->first('password_confirmation') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-8 offset-md-4">
                                            <button type="submit" class="btn btn-primary">
                                                {{ __('Submit') }}
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    @include('layouts.navtab')
                    <div class="card-body">
                        <div class="row">
                            @include('layouts.sidebar')
                            <div class="col-md-8">

                                @if(Session::has('message'))
                                    <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                                @endif

                                <form action="/user/{{ $user->id }}" method="post">
                                    @csrf
                                    @method('PUT')

                                    <div class="form-group row">
                                        <label for="first_name" class="col-sm-4 col-form-label text-md-right">{{ __('First name') }}</label>

                                        <div class="col-md-6">
                                            <input id="first_name" type="text"
                                                   class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}"
                                                   name="first_name"
                                                   value="{{ old('first_name', $user->first_name) }}">
                                            @if ($errors && $errors->has('last_name'))
                                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                            @endif
                                        </div>

                                    </div>

                                    <div class="form-group row">
                                        <label for="last_name" class="col-sm-4 col-form-label text-md-right">{{ __('Last name') }}</label>

                                        <div class="col-md-6">
                                            <input id="last_name" type="text"
                                                   class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}"
                                                   name="last_name" value="{{ old('last_name', $user->last_name) }}">
                                            @if ($errors && $errors->has('last_name'))
                                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                            @endif
                                        </div>

                                    </div>

                                    <div class="form-group row">
                                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                                        <div class="col-md-6">
                                            <input id="email" type="email"
                                                   class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                                   name="email" value="{{ old('email', $user->email) }}">
                                            @if ($errors->has('email'))
                                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                                        <div class="col-md-6">
                                            <input id="phone" type="tel"
                                                   class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}"
                                                   name="phone" value="{{ old('phone', $user->phone) }}">
                                            @if ($errors->has('phone'))
                                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="birth_year" class="col-md-4 col-form-label text-md-right">{{ __('Year of birth') }}</label>

                                        <div class="col-md-6">
                                            <input id="birth_year" type="year"
                                                   class="form-control{{ $errors->has('birth_year') ? ' is-invalid' : '' }}"
                                                   name="birth_year"
                                                   value="{{ old('birth_year', $user->birth_year) }}">
                                            @if ($errors->has('birth_year'))
                                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('birth_year') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="about" class="col-md-4 col-form-label text-md-right">{{ __('About me') }}</label>

                                        <div class="col-md-6">
                                    <textarea id="about" name="about" rows="5" placeholder="{{ __('Tell us about yourself.') }}"
                                              class="form-control{{ $errors->has('about') ? ' is-invalid' : '' }}">{{ old('about', $user->about) }}</textarea>
                                            @if ($errors->has('about'))
                                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('about') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-8 offset-md-4">
                                            <button type="submit" class="btn btn-primary">
                                                {{ __('Save') }}
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-body">

                        <div class="offset-md-3 col-md-6">

                            @if (Session::has('success'))
                                <div class="alert alert-success">{{ Session::get('success') }}</div>
                            @endif
                            @if (Session::has('failure'))
                                <div class="alert alert-danger">{{ Session::get('failure') }}</div>
                            @endif

                            <div class="text-md-center">
                                <img src="{{ $user->profile_image }}" alt="Profile image" class="profile-image">
                                <h4>{{ $user->full_name }}</h4>
                                @if(isset($user->birth_year))
                                    <p>{{ $user->age }} {{ __('y.o.') }}</p>
                                @endif
                                @if(isset($user->about))
                                    <p>{{ $user->about }}</p>
                                @endif
                            </div>
                            <hr>
                            <p>Email: {{ $user->email }}</p>
                            <hr>
                            <p class="small margin-0">{{ __('Offered trips:') }} {{ $countUserTravels }}</p>
                            <p class="small"> {{ __('Registered at:') }} {{ $user->register_month }}</p>
                            <hr>
                            @if(!$reviews->isEmpty())
                                @if(isset($user->avg_score))
                                    <h5>{{ __('Rating:') }} {{ $user->avg_score }}/5 -
                                        {{ $reviewsCount }} {{ __('feedback') }}
                                    </h5>
                                @endif

                                @foreach($reviews as $review)
                                    <hr>
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-3 offset-lg-3 offset-md-4">
                                            <img src="{{ $review->owner->profile_image }}"
                                                 alt="Profile image" class="profile-image-small">
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-md-left text-lg-left">
                                            <p><b>{{ $review->literal_score }}</b></p>
                                            <p><b>From
                                                    <a href="/user/{{ $review->owner->id }}">
                                                        {{ $review->owner->first_name }}
                                                    </a>
                                                </b>: {{ $review->about }}
                                            </p>
                                            <p class="small">{{ $review->literal_created_at }}</p>
                                        </div>
                                    </div>
                                @endforeach
                                {{ $reviews->links() }}

                            @else
                                <p>{{ __('No feedback for') }} {{ $user->first_name }}</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection