routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Auth::routes()
;
Route::get('/', 'WelcomeController@index');

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

//CityController
Route::get('search', 'CityController@search');

//CarController
Route::get('searchBrand', 'CarController@searchBrand');
Route::get('searchModel', 'CarController@searchModel');
Route::get('user/car', 'CarController@index')->name('car.index');
Route::post('user/car', 'CarController@store')->name('car.store');
Route::delete('user/car', 'CarController@destroy')->name('car.destroy');

//TravelController
Route::get('travel/offered', 'TravelController@offered')->name('travel.offered');
Route::get('travel/offered/history', 'TravelController@offeredHistory')->name('travel.offered_history');
Route::get('travel/booked', 'TravelController@booked')->name('travel.booked');
Route::get('travel/booked/history', 'TravelController@bookedHistory')->name('travel.booked_history');
Route::get('travel/{travel}/book', 'TravelController@book')->name('travel.book');
Route::delete('travel/{travel}/cancel_booking', 'TravelController@cancelBooking');
Route::resource('travel', 'TravelController');

//UserImageController
Route::get('image', 'UserImageController@index')->name('image');
Route::post('image/upload', 'UserImageController@upload')->name('image.upload');
Route::delete('image/delete', 'UserImageController@delete')->name('image.delete');

//UpdatePasswordController
Route::get('user/change-password', 'UpdatePasswordController@index')->name('password.form');
Route::put('user/change-password', 'UpdatePasswordController@update')->name('password.update');

//UserController
Route::get('user/edit', 'UserController@edit')->name('user.edit');
Route::get('user/remove', 'UserController@remove')->name('user.remove');
Route::get('user/{user}', 'UserController@show')->name('user.show');
Route::put('user/{user}', 'UserController@update')->name('user.update');
Route::delete('user/{user}', 'UserController@destroy')->name('user.destroy');

//ReviewController
Route::get('review/received', 'ReviewController@received')->name('review.received');
Route::get('review/leaved', 'ReviewController@leaved')->name('review.leaved');
Route::get('review/create/{user}/{travel}', 'ReviewController@create')->name('review.create');
Route::post('review/{user}/{travel}', 'ReviewController@store')->name('review.store');

//HomeController
Route::get('home', 'HomeController@index')->name('home');

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Car
 *
 * @property int $id
 * @property int $year
 * @property string $brand
 * @property string $model
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Car whereBrand($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Car whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Car whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Car whereModel($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Car whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Car whereYear($value)
 * @mixin \Eloquent
 */
class Car extends Model
{
    const CARS_IN_SEARCH_LIST = 10;
    const SEARCH_BY_BRAND = 'brand';
    const SEARCH_BY_MODEL = 'model';

    /**
     * The table associated with the model.
     * @var string
     */
    protected $table = 'car';


    public function getFullNameAttribute()
    {
        return $this->brand.' '.$this->model;
    }

}

app/Models/Review.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Review
 *
 * @package App
 * @property int $id
 * @property int $owner_id
 * @property int $user_id
 * @property int $travel_id
 * @property int $type
 * @property string $score
 * @property string $about
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $owner
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereOwnerId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereScore($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereUserId($value)
 * @mixin \Eloquent
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereTravelId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Review whereType($value)
 */
class Review extends Model
{

    const SCORE = [
        '5' => 'Outstanding',
        '4' => 'Excellent',
        '3' => 'Good',
        '2' => 'Poor',
        '1' => 'Very disappointing',
    ];

    const REVIEWS_PER_PAGE = 5;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'review';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable = [
        'score',
        'about',
        'type',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function owner()
    {
        return $this->belongsTo('App\Models\User', 'owner_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    /**
     * @return string
     */
    public function getLiteralScoreAttribute(): string
    {
        return array_key_exists($this->score, self::SCORE)
            ? self::SCORE[$this->score]
            : 'Unknown score';// const
    }

    /**
     * @return string
     */
    public function getLiteralCreatedAtAttribute(): string
    {
        return date("F jS - g:ia", strtotime($this->created_at));
    }

}

app/Models/Travel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Travel
 *
 * @package App
 * @property integer $id
 * @property City $start_id
 * @property City $destination_id
 * @property string $date
 * @property string $time
 * @property integer $price
 * @property string $about
 * @property integer $free_places
 * @property User $user_id
 * @property integer $status
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon $updated_at
 * @property-read \App\Models\City $destination_city
 * @property-read \App\Models\City $start_city
 * @property-read \App\Models\User|null $user
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $passengers
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereDestinationId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereFreePlaces($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereStartId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Travel whereUserId($value)
 */
class Travel extends Model
{

    const SINGLE_TRAVEL_REVIEWS = 2;
    const TRAVELS_PER_PAGE = 5;
    const TRAVELS_HISTORY = '<';
    const TRAVELS_CURRENT = '>=';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'travel';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable = [
        'start_id',
        'destination_id',
        'date',
        'time',
        'price',
        'about',
        'free_places',
        'user_id',
    ];

    public function start_city()
    {
        return $this->belongsTo('App\Models\City', 'start_id', 'city_id');
    }

    public function destination_city()
    {
        return $this->belongsTo('App\Models\City', 'destination_id', 'city_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    public function passengers()
    {
        return $this->belongsToMany('App\Models\User', 'user_to_travel');
    }

    /**
     * @return string
     */
    public function getFullTimeAttribute(): string
    {
        return date("F jS Y", strtotime($this->date)) . ' - ' . date('g:ia', strtotime($this->time));
    }

    /**
     * @return string
     */
    public function getFullTravelAttribute(): string
    {
        return $this->start_city->name . ' -> ' . $this->destination_city->name;
    }

    /**
     * @return string
     */
    public function getPublicationDateAttribute(): string
    {
        return date("F jS - g:ia", strtotime($this->created_at));
    }

    /**
     * @return int
     */
    public function getAvailablePlacesAttribute(): int
    {
        return $this->free_places;
    }

    /**
     * @return float
     */
    public function getAvgScoreAttribute(): float
    {
        return round($this->user->review->pluck('score')->avg(), 1);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 *
 * @package App
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property integer $birth_year
 * @property string $about
 * @property string $car
 * @property string $image
 * @property integer $status
 * @property integer $admin
 * @property integer $password
 * @property integer $remember_token
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Travel[] $passenger
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Review[] $review
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Travel[] $travel
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\UserToTravel[] $usersPassengers
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereAdmin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereBirthYear($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereUpdatedAt($value)
 * @property int|null $car_id
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereCarId($value)
 */
class User extends Authenticatable
{
    use Notifiable;

    const DEFAULT_PROFILE_IMAGE = '/images/default.jpg';
    const PROFILE_IMAGE_PATH = '/uploads/images/profile/';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'phone', 'birth_year', 'about', 'image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    protected static function boot()
    {
        parent::boot();

        static::deleting(function (User $user) {
            $user->passenger()->detach();
            $user->usersPassengers()->delete();
            $user->review()->delete();
            $user->usersReviews()->delete();
            $user->travel()->delete();
            $user->deleteImage();
        });
    }

    public function review()
    {
        return $this->hasMany('App\Models\Review');
    }

    public function usersReviews()
    {
        return $this->belongsTo('App\Models\Review', 'id', 'owner_id');
    }

    public function travel()
    {
        return $this->hasMany('App\Models\Travel');
    }

    public function usersPassengers()
    {
        return $this->hasManyThrough('App\Models\UserToTravel', 'App\Models\Travel');
    }

    public function passenger()
    {
        return $this->belongsToMany('App\Models\Travel', 'user_to_travel');
    }

    public function car()
    {
        return $this->hasOne('App\Models\Car', 'id', 'car_id');
    }

    /**
     * Removes users image
     * return void
     */
    public function deleteImage(): void
    {
        $imagePath = public_path(). self::PROFILE_IMAGE_PATH . $this->image;
        if(isset($this->image) && file_exists($imagePath))
        {
            unlink($imagePath);
        }
    }

    /**
     * @return string
     */
    public function getProfileImageAttribute(): string
    {
        $path = self::PROFILE_IMAGE_PATH;
        $pathToProfileImage = public_path() . $path . $this->image;
        return !empty($this->image) && file_exists($pathToProfileImage) ?
            $path . $this->image : self::DEFAULT_PROFILE_IMAGE;
    }

    /**
     * @return string
     */
    public function getShortNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name{0};
    }

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @return int
     */
    public function getAgeAttribute()
    {
        return date('Y') - $this->birth_year;
    }

    /**
     * @return string
     */
    public function getRegisterMonthAttribute()
    {
        return date("F Y", strtotime($this->created_at));
    }

    /**
     * @return float
     */
    public function getAvgScoreAttribute(): float
    {
        return round($this->review->pluck('score')->avg(), 1);
    }

}

resources/views/travel/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @if(!$travels->isEmpty())
                            <h4>{{ $travelsCount }} trip{{$travelsCount === 1 ? '' : 's'}} are found.</h4>

                            @foreach($travels as $travel)
                                <div class="row border single-travel">
                                    <div class="col-sm-4 border-right">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <img src="{{ $travel->user->profile_image }}"
                                                     class="profile-image" alt="Profile image">
                                            </div>
                                            <div class="col-sm-6">
                                                <a href="/user/{{ $travel->user->id }}">{{ $travel->user->short_name }}</a>
                                                @if(isset($travel->user->birth_year))
                                                    <p class="small">age: {{ $travel->user->age }} y.o.</p>
                                                @endif
                                                @if(isset($travel->user->car))
                                                    <p class="small">car: {{ $travel->user->car->full_name }}</p>
                                                @endif
                                            </div>
                                        </div>
                                        @if($travel->avg_score)
                                            <p class="text-md-center"><i class="far fa-star"></i>
                                                rating: {{ $travel->avg_score }}/5 -
                                                <a href="/user/{{ $travel->user->id }}">
                                                    {{ $count = count($travel->user->review) }}
                                                    rating{{ $count > 1 ? 's' : '' }}
                                                </a>
                                            </p>
                                        @else
                                            <p class="text-md-center">No feedback</p>
                                        @endif
                                    </div>
                                    <div class="col-sm-6">
                                        <h4>{{ $travel->full_time }}</h4>
                                        {{ $travel->full_travel }}
                                        <br>
                                        <a class="btn btn-primary" href="/travel/{{ $travel->id }}">More info</a>
                                    </div>
                                    <div class="col-sm-2">
                                        <h2>₴{{ $travel->price }}</h2>
                                        <span class="small">per passenger</span>
                                        <p><b>{{ $travel->free_places }}</b> available seats</p>
                                    </div>
                                </div>
                            @endforeach
                            {{ $travels->links() }}

                        @else
                            <p>No results found.</p>
                        @endif

                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/travel/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-body">

                        <div class="col-md-12">
                            <p class="small text-right">{{ __('Publication date:') }} {{ $travel->publication_date }} </p>
                        </div>
                        <div class="row cell">
                            <div class="col-sm-8 border">
                                <table class="table table-borderless">
                                    <tbody>
                                    <tr>
                                        <td>{{ __('Place of departure:') }}</td>
                                        <th><i class="fa fa-map-marker-alt"></i>
                                            {{ $travel->start_city->name }}</th>
                                    </tr>
                                    <tr>
                                        <td>{{ __('Place of arrival:') }}</td>
                                        <th><i class="fa fa-map-marker-alt"></i>
                                            {{ $travel->destination_city->name }}</th>
                                    </tr>
                                    <tr>
                                        <td>{{ __('Date:') }}</td>
                                        <th><i class="fa fa-calendar-alt"></i>
                                            {{ $travel->full_time }}</th>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            @if(isset($travel->about))
                                                {{ __('Additional information:') }} {{ $travel->about }}
                                            @else
                                                {{ $travel->user->first_name }} {{ __('didn\'t provide additional
                                                information.') }}
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            @if(!$travel->passengers->isEmpty())
                                                <p>{{ __('Passengers in this ride:') }}</p>
                                                @foreach($travel->passengers as $passenger)
                                                    <a href="/user/{{ $passenger->id }}"
                                                       title="{{ $passenger->first_name }}">
                                                        <img src="{{ $passenger->profile_image }}"
                                                             class="profile-image-small" alt="Profile image">
                                                    </a>
                                                @endforeach
                                                <br>
                                            @else
                                                <p>{{ __('No passengers in this ride.') }}</p>
                                            @endif
                                            <br>

                                            @if (Session::has('success'))
                                                <div class="alert alert-success">{{ Session::get('success') }}</div>
                                            @endif
                                            @if (Session::has('failure'))
                                                <div class="alert alert-danger">{{ Session::get('failure') }}</div>
                                            @endif

                                            @can('update', $travel)
                                                <a href="/travel/{{ $travel->id }}/edit"
                                                   class="btn-warning btn show-btn">{{ __('Edit ride') }}</a>
                                            @endcan

                                            @can('book', $travel)
                                                <div class="alert alert-info">
                                                    <strong>{{ __('Note: This booking will be confirmed automatically.') }}</strong>
                                                </div>
                                                <a href="/travel/{{ $travel->id }}/book" class="btn-success btn"
                                                   onclick="return confirm('{{ __("Do you want to book this ride?") }}')">{{ __('Book ride') }}</a>
                                            @endcan

                                            @can('cancelBooking', $travel)
                                                <form action="/travel/{{ $travel->id }}/cancel_booking" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-danger"
                                                                onclick="return confirm('{{ __("Do you want to cancel ride?") }}')">
                                                            {{ __('Cancel booking') }}
                                                        </button>
                                                    </div>
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-sm-4">
                                <div class="row">
                                    <div class="col-md-6 text-md-center border">
                                        <h2 class="margin-top">₴{{ $travel->price }}</h2>
                                        <p class="small">{{ __('per passenger') }}</p>
                                    </div>
                                    <div class="col-md-6 text-md-center border">
                                        <h2 class="margin-top"><i
                                                    class="fas fa-car"></i> {{ $travel->available_places }}</h2>
                                        <p class="small">{{ __('available seats') }}</p>
                                    </div>
                                    <div class="col-md-12 border">
                                        <p class="margin-top"><b>{{ __('Driver') }}</b></p>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <img src="{{ $travel->user->profile_image }}"
                                                     class="profile-image" alt="Profile image">
                                            </div>
                                            <div class="col-sm-6">
                                                <a href="/user/{{ $travel->user->id }}">
                                                    <h4>{{ $travel->user->short_name }}</h4></a>
                                                @if(isset($travel->user->birth_year))
                                                    <p class="small small-cell">{{ __('age:') }} {{ $travel->user->age }} {{ __('y.o.') }}</p>
                                                @endif
                                                @if(isset($travel->avg_score))
                                                    <p class="small">{{ __('rating:') }} {{ $travel->avg_score }}/5 -
                                                        <a href="/user/{{ $travel->user->id }}">
                                                            {{ $count = count($travel->user->review) }}
                                                            {{ __('rating') }}
                                                        </a>
                                                    </p>
                                                @endif
                                            </div>
                                            <div class="col-md-12">
                                                <hr>
                                                @if(isset($travel->user->car))
                                                    <p><b>{{ __('Car') }}</b></p>
                                                    <p>{{ $travel->user->car->full_name }}</p>
                                                    <hr>
                                                @endif
                                                @if(isset($travel->user->review))
                                                    <p><b>{{ __('Reviews') }}</b>
                                                        <span class=float-right><a href="/user/{{ $travel->user->id }}">{{ __('Watch all reviews') }}</a></span>
                                                    </p>
                                                    @foreach($travel->user->review as $review)
                                                        <div class="row">
                                                            <div class="col-md-12 text-md-center">
                                                                <img src="{{ $review->owner->profile_image }}"
                                                                     alt="Profile image" class="profile-image-small">
                                                            </div>
                                                            <div class="col-md-12 text-md-center">
                                                                <p><b>{{ $review->literal_score }}</b></p>
                                                                <p><b>{{ __('From') }}
                                                                        <a href="/user/{{ $review->owner->id }}">
                                                                            {{ $review->owner->first_name }}
                                                                        </a>
                                                                    </b>: {{ $review->about }}
                                                                </p>
                                                                <p class="small">{{ $review->literal_created_at }}</p>
                                                            </div>
                                                        </div>
                                                        <hr>
                                                    @endforeach
                                                @else
                                                    <p>{{ __('No feedback for') }} {{ $travel->user->first_name }}</p>
                                                    <hr>
                                                @endif
                                                <p><b>{{ __('User\'s activity') }}</b></p>
                                                <p>{{ __('Offered trips:') }} {{ $countDriversTravels }}</p>
                                                <p>{{ __('Registered at:') }} {{ $travel->user->register_month }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection